Introduce single `build_and_test.yml`  for building and testing eventuals
3rdparty/eventuals pull request #194
Opened 2022-01-20 09:08 UTC by ArthurBandaryk

We can use `matrix` and have only 1 .yml file which can do building and running all tests for eventuals on macOS, Ubuntu and Windows.

2022-01-20 10:10 UTC, while-false approved these changes
Thanks Arthur!

2022-01-20 10:18 UTC, FolMing commented
Is there a way to optimize away those "Debug smth using tmate (if failure)" steps? And also, seeing all of the skipped actions is a bit distracting and confusing.

I would love it if it was more like this:
- Build
- Test
- Debug on any failure

2022-01-21 03:13 UTC, benh requested changes

2022-01-21 03:13 UTC, benh commented on .github/workflows/build_and_test.yml
> +        run: bazel test --spawn_strategy=local --strip="never" --test_output=errors test:eventuals --test_arg=--gtest_shuffle --test_arg=--gtest_repeat=100
Does it work if we do `-c dbg` for Windows? Then we can have a single Build step and single Test step with no `if`. Also let's wrap these long lines, I've been meaning to do that for a while. See suggestion below for both!
 
```suggestion
      - name: Build
        run: bazel build \
               --spawn_strategy=local \
               -c dbg \
               --strip="never" \
               :eventuals

      - name: Test
        run: bazel test \
               --spawn_strategy=local \
               -c dbg \
               --strip="never" \
               --test_output=errors \
               test:eventuals \
               --test_arg=--gtest_shuffle \
               --test_arg=--gtest_repeat=100
```

2022-01-21 03:14 UTC, benh commented
> Is there a way to optimize away those "Debug smth using tmate (if failure)" steps? And also, seeing all of the skipped actions is a bit distracting and confusing.
> 
> I would love it if it was more like this:
> 
> * Build
> * Test
> * Debug on any failure

I think that actually will work @FolMing! Let's give it a try @ArthurBandaryk, only include the debug step at the end!

2022-01-21 11:53 UTC, FolMing approved these changes
Now it looks super clean, thank you!

2022-01-21 16:33 UTC, benh approved these changes

2022-01-24 08:52 UTC, merged