Errors
3rdparty/eventuals pull request #237
Opened 2022-03-02 22:51 UTC by onelxj

2022-03-02 22:52 UTC, onelxj commented
Need to be rebased this after [this](https://github.com/3rdparty/eventuals/pull/237/commits/9eab308e4deada4c3183b9f166cd8dbb1cd31363) one.

2022-03-03 04:46 UTC, benh requested changes

2022-03-03 04:46 UTC, benh commented on test/task.cc
> +              .template raises<std::runtime_error>();
That's some kung fu magic! Let's be explicit for our poor readers, and then if the `Just()` implementation ever changes in the future this line of code won't break awkwardly.
```suggestion
return Eventual<int>()
    .template raises<std::runtime_error>()
    .start([&](auto& k) {
      return k.Start(i);
    });
```

2022-03-03 04:46 UTC, benh commented on test/task.cc
> +            .raises<std::runtime_error>();
See other comment!

2022-03-03 04:46 UTC, benh commented on test/task.cc
> +      return Task::Success<int, std::runtime_error>(10);
Let's make our API not require specifying the error type when we know we're successful!

2022-03-03 04:46 UTC, benh commented on eventuals/task.h
> +        std::tuple<Errors...>>(std::move(value));
Errors is always empty! See [here in expected.h](https://github.com/3rdparty/eventuals/blob/main/eventuals/expected.h#L193).

2022-03-03 04:46 UTC, benh commented on eventuals/task.h
> +        std::tuple<Errors...>>(std::monostate{});
See comment above.

2022-03-03 04:46 UTC, benh commented on eventuals/task.h
> +struct TaskBuilder final
I LOVE THIS BUILDER PATTERN! GREAT IDEA!!!

Once we settle on the exact naming let's do the same in expected.h.

2022-03-03 04:46 UTC, benh commented on eventuals/task.h
> +  using From = TaskBuilder<T, To_, Errors_, Args_...>;
What happens if someone does `From<>` more than once when building? Can we add `has_from_` fields and do:

```cpp
template <typename T>
using From = std::enable_if_t<!has_from_, TaskBuilder<...>>;
```

2022-03-03 04:46 UTC, benh commented on eventuals/task.h
> +  using Of = TaskBuilder<void, T, Errors_, Args_...>;
Since `Of` is an alias for both `From` and `To` then we can check in the `std::enable_if_t` as appropriate!

2022-03-03 04:46 UTC, benh commented on eventuals/task.h
> +        Args_...>(std::move(args)..., std::move(f)) {}
We should be able to just replace all of this with:

```suggestion
    using TaskFromToWith<..., ..., etc>::TaskFromToWith;
```

See how we did this in [`expected.h`](https://github.com/3rdparty/eventuals/blob/main/eventuals/expected.h#L178).

2022-03-03 04:46 UTC, benh commented on eventuals/task.h
> +  TaskBuilder(TaskBuilder&&) = default;
Shouldn't need this because of comment above!

2022-03-03 04:46 UTC, benh commented on eventuals/task.h
> +  ~TaskBuilder() = default;
```suggestion
  ~TaskBuilder() override = default;
```

2022-03-03 04:46 UTC, benh commented on eventuals/task.h
> +    : TaskFromToWith<From_, To_, Errors_, Args_...>(std::move(value)) {}
Again, shouldn't need this by pulling in parent constructors, didn't think of this when we were doing it before but it should work!

2022-03-21 02:21 UTC, benh requested changes

2022-03-21 02:21 UTC, benh commented on test/generator.cc
> +  auto task = [&]() -> Task::Of<std::vector<int>>::Raises<std::exception> {
I don't understand why we have to use `Raises` if it doesn't raise anything?

2022-03-21 02:21 UTC, benh commented on eventuals/task.h
> +  template <typename Arg, typename Errors = std::tuple<>>
No default here, someone should always give us the errors to start with.
```suggestion
  template <typename Arg, typename Errors>
```

2022-03-21 02:21 UTC, benh commented on eventuals/task.h
> +  }
```suggestion
```

2022-03-21 02:21 UTC, benh commented on eventuals/task.h
> +    : e_(std::move(that.e().value_or_dispatch_), std::move(that.e().args_)) {
```suggestion
    : e_(std::move(that.e_.value_or_dispatch_), std::move(that.e_.args_)) {
```

2022-03-21 02:21 UTC, benh commented on eventuals/task.h
> +          "Specified errors can't be thrown from 'Task'");
```suggestion
          "Specified errors can't be raised within 'Task'");
```

2022-03-21 02:21 UTC, benh commented on eventuals/task.h
> +  template <typename Value, typename... Errors>
Success never has errors!
```suggestion
  template <typename Value>
```

2022-03-21 14:56 UTC, onelxj commented on eventuals/task.h
> +  }
Should we make 'e_' public instead?

2022-03-26 07:34 UTC, benh approved these changes

2022-03-26 07:34 UTC, benh commented on eventuals/task.h
> +      Error&& arg,
```suggestion
      Error&& error,
```

2022-03-26 07:34 UTC, benh commented on eventuals/task.h
> +class TaskFromToWith final {
```suggestion
class _Task final {
```

2022-03-28 20:23 UTC, merged