Fix bug on Windows with poll initialization for sockets
3rdparty/eventuals pull request #344
Opened 2022-04-19 22:22 UTC by benh

2022-04-19 23:24 UTC, onelxj approved these changes

2022-04-19 23:24 UTC, onelxj commented on eventuals/event-loop.h
> +      void
Restore?

2022-04-19 23:35 UTC, onelxj commented on eventuals/event-loop.h
> +#if !defined(_WIN32)
Maybe `#ifndef` could be better there?

2022-04-20 01:37 UTC, FolMing commented
Come on, guys, why approve? This doesn't work at all!

1. GetFileType requires #include <fileapi.h>
2. GetFileType expects HANDLE as a parameter and not a random integer.

Even after fixing the above things (using reinterpret_cast for the 2.) the test executable crashes:
![image](https://user-images.githubusercontent.com/11060773/164129392-b317a494-7cc3-4cbf-a51a-2f4e0d4298b8.png)

2022-04-20 01:40 UTC, FolMing requested changes

2022-04-20 01:40 UTC, FolMing commented on eventuals/event-loop.h
> +                if (GetFileType(fd_) == FILE_TYPE_PIPE) {
1. GetFileType requires #include <fileapi.h>
2. GetFileType expects HANDLE as a parameter and not a random integer.

2022-04-20 01:59 UTC, FolMing commented
#346 should fix the issues above.

2022-04-21 16:08 UTC, FolMing approved these changes

2022-04-25 11:33 UTC, merged