Introduce google failure signal handler
3rdparty/eventuals pull request #403
Opened 2022-05-19 09:57 UTC by ArthurBandaryk

Earlier we had absolutely horrible stack trace on `glog` check failure, like in example below:
![stack](https://user-images.githubusercontent.com/68085133/169266701-0b73a9a8-e0d0-4ac8-a7d0-468d007ce528.png)

This PR introduces a convenient [signal handler](https://github.com/google/glog#failure-signal-handler) that will dump useful information when the program crashes on certain signals such as SIGSEGV. The signal handler can be installed by `google::InstallFailureSignalHandler()` from `glog` library.

2022-05-20 13:46 UTC, onelxj commented on test/BUILD.bazel
> +    name = "environment",
What do you think about `test_environment`?

2022-05-20 13:46 UTC, onelxj commented on test/signal-handler-env.h
> +  // Override this to define how to set up the environment.
remove please

2022-05-20 13:46 UTC, onelxj commented on test/signal-handler-env.h
> +  // Override this to define how to tear down the environment.
remove please

2022-05-20 13:46 UTC, onelxj commented on test/stack-trace-check.cc
> +// Including eventuals stuff.
remove please

2022-05-21 21:48 UTC, benh requested changes

2022-05-21 21:48 UTC, benh commented on test/stack-trace-check.cc
> +TEST(StackTrace, CheckFail) {
This file is great for testing but let's not include it when we merge, thanks!

2022-05-21 21:48 UTC, benh commented on test/stack-trace-check.cc
> +    testing::AddGlobalTestEnvironment(new SignalHandlerEnvironment{});
This will need to be in a different `.cc` in the tests.

2022-05-24 04:13 UTC, benh requested changes

2022-05-24 04:13 UTC, benh commented on test/BUILD.bazel
> +cc_library(
Why does this need to be its own library?

2022-05-25 20:12 UTC, merged