Prefer constructor to extra 'Lazy(Args&&... args)' function
3rdparty/eventuals pull request #404
Opened 2022-05-20 09:35 UTC by ArthurBandaryk

2022-05-21 19:52 UTC, benh requested changes

2022-05-21 19:52 UTC, benh commented on eventuals/lazy.h
> +class Lazy final {
```suggestion
template <typename T_, typename... Args_>
class Lazy final {
 public:
   template <typename... Args>
   using Args = std::enable_if_t<sizeof...(Args_) == 0, Lazy<T_, Args...>>;
   
   Lazy(Args_&&... args)
    : args_(std::forward<Args_>(args)...) {}
    
  Lazy(Lazy&& that)
    : args_(std::move(that.args_)) {
    CHECK(!t_) << "'Lazy' can not be moved after using";
  }
```

2022-05-21 19:52 UTC, benh commented on eventuals/lazy.h
> +  Lazy(Tuple args)
Can you see if we can delete this one and instead always pass the 'args' and construct the tuple from that?

2022-05-24 10:12 UTC, onelxj approved these changes
LGTM!

2022-05-24 15:15 UTC, benh requested changes

2022-05-26 13:50 UTC, onelxj approved these changes

2022-05-30 03:06 UTC, benh approved these changes

2022-05-30 03:06 UTC, benh commented on eventuals/lazy.h
> +  using Args = std::enable_if_t<sizeof...(Args_) == 0, _Lazy<T_, Args...>>;
To ensure someone can't do `Lazy::Of<Foo>::Args<>::Args<int>`:

```suggestion
  template <typename Arg, typename... Args>
  using Args = std::enable_if_t<sizeof...(Args_) == 0, _Lazy<T_, Arg, Args...>>;
```

2022-05-30 09:25 UTC, merged