Change visibility of 'backward' target to 'public'
3rdparty/eventuals pull request #462
Opened 2022-07-15 10:31 UTC by ArthurBandaryk

We need to change the visibility of 'test:backward' target
because we are planing to use it not onli in '3rdparty/eventuals'
but in 'reboot-dev/respect' repo too.

2022-07-15 10:32 UTC, FolMing commented
If we are using it in multiple repos, how about moving it over to bazel-rules?

2022-07-15 10:34 UTC, CodingCanuck commented
> If we are using it in multiple repos, how about moving it over to bazel-rules?

I like this suggestion: looking through https://github.com/3rdparty/eventuals/blob/main/test/backward-stacktrace.h and https://github.com/3rdparty/eventuals/blob/main/test/backward-stacktrace.cc they appear to have no dependencies on the rest of eventuals, so this doesn't seem to need to live in the eventuals repo.

2022-07-15 10:34 UTC, ArthurBandaryk commented
> If we are using it in multiple repos, how about moving it over to bazel-rules?

I think this would be too much redundant. By the way 'promisify-for-test' has the same strategy as mine

2022-07-15 10:37 UTC, CodingCanuck requested changes
Can you please explore Nik's suggestion of providing this in the `backward`-specific repo, rather than in `eventuals`? (That feels attractive because the code you're exposing isn't specific to eventuals)

2022-07-15 10:46 UTC, FolMing commented
BTW, the compilation time is super nice now thanks to cache 😋

2022-07-18 06:53 UTC, CodingCanuck approved these changes

2022-07-18 06:53 UTC, CodingCanuck commented on test/BUILD.bazel
> -cc_library(
Please update the PR description: this PR no longer changes `backward`'s visibility

2022-07-18 09:57 UTC, merged